### PR TITLE
Spark sas&bdat 2.0.0

### PR DESCRIPTION
**Pull request by gbisschoff**
upgrade the spark.sas7bdat to the latest version (2.0.0)

### CODE REVIEW

**Comment by jwijffels** [comment]
Thanks!

**Comment by jwijffels** [comment]
Do you also have code which ships the package itself instead of downloading from https://spark-packages.org?

**Comment by gbisschoff** [comment]
You mean by having the .jar file as a local dependency that then does not have to be downloaded?

**Comment by jwijffels** [comment]
yes

**Comment by gbisschoff** [comment]
Yes I do somewhere. I will find it and submit a pull request. I actually did it to get past my company proxy that didn't want to pull the .jar dependencies.

**Pull request merged**
